name: SMPizza
version: 1.0
api-version: 1.17
description: Pizza
author: Jeeper_
main: smp.pizza.Main
commands:
  chatcolor:
    description: Sets the player's name in chat!
    aliases: [color, setcolor, cc]
  smpizza:
    description: used to reload yml files
    default: op
    permission: smpizza.reload
  cd:
    description: cd command for CustomDiscs plugin
    aliases: [customdisc]
  mod:
    description: gives a player the moderator tag
    default: op
    permission: smpizza.mod
  admin:
    description: gives a player the administrator tag
    default: op
    permission: smpizza.admin
  member:
    description: gives a player the member tag
    default: op
    aliases: [unmod, unadmin]
    permission: smpizza.member
  ping:
    description: send a player their ping
  mute:
    description: mute a player
    default: op
    permission: smpizza.mute
  unmute:
    description: unmute a player
    default: op
    permission: smpizza.mute
  hat:
    description: put something on your head